# Generated by Django 4.2.5 on 2023-09-14 06:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="listings",
            name="price",
            field=models.FloatField(default=90, max_length=10),
            preserve_default=False,
        ),
    ]
