# Generated by Django 4.2.5 on 2023-09-16 16:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0002_listings_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="listings",
            name="watchlist",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="l_watchlist",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="listings",
            name="imageUrl",
            field=models.URLField(blank=True, null=True),
        ),
    ]
