# Generated by Django 4.2.5 on 2023-09-18 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0007_alter_listings_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listings",
            name="price",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="auctions.bid"
            ),
        ),
    ]
