# Generated by Django 4.2.5 on 2023-09-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0008_alter_listings_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bid",
            name="bid",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=30.0, max_digits=10, null=True
            ),
        ),
    ]
