# Generated by Django 4.2.5 on 2023-09-18 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0009_alter_bid_bid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bid",
            name="bid",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="listings",
            name="price",
            field=models.ForeignKey(
                default=40.0,
                on_delete=django.db.models.deletion.CASCADE,
                to="auctions.bid",
            ),
        ),
    ]
