# Generated by Django 4.2.5 on 2023-09-18 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0011_remove_bid_listing_alter_listings_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="bid",
            name="listing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="auctions.listings",
            ),
        ),
    ]
