# Generated by Django 4.2.6 on 2023-10-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0013_listings_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bid",
            name="bid",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=50, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="listings",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
